### ISSUE TITLE
Can't get wooden lava bucket

### ISSUE THREAD

**Issue by dlswimmer** [Kikiisyourfriend/ProjectIsothermalExpert#1]
The wooden lava bucket is needed for two quests (one for itself and the other for the cobble gen), but there is no recipe for the wooden lava bucket. I thought to just make a bucket and get lava out of the squeezer, but as soon as you do the bucket transforms into a metal bucket with lava

**Comment by itsjusttriz** [comment]
This problem has been reproduced on stream and will be hopefully fixed in a future update. Thanks for reporting the issue.

**Comment by Kikiisyourfriend** [comment]
Thank you for reporting this @dlswimmer The problem has been fixed by completely removing Wooden Buckets from the pack. Now Iron buckets are in play. This will be applied to our next pack update tonight. I appreciate you!

**Comment by Kikiisyourfriend** [comment]
This fix has been applied and approved with version 0.3.0!
