### ISSUE TITLE
[BUG] - Rip Pillager Egg

### ISSUE THREAD

**Issue by itsjusttriz** [Kikiisyourfriend/ProjectIsothermalExpert#10]
### **Confirm your current modpack version:**

```
0.3.5 (latest)
```
### **Are you on a server? Or in Singleplayer?:**

```
Singleplayer
```

### **Description:**

```
I think the Pillager Egg quest may have been accidentally reset in the latest
update causing a progress reset for this quest for all players.

Also the reward is missing for it.
```

### **Steps to reproduce:**

```
Check Quest Book -> Eggs Tab.
```
### **Crash log (*if any*):**
> *Must use a code-pasting website such as Pastebin, or a Gist.*

```
N/A
```

**Comment by Kikiisyourfriend** [comment]
egg is new to quest. reward added
