### ISSUE TITLE
[BUG] - Gold to Diamond?

### ISSUE THREAD

**Issue by itsjusttriz** [Kikiisyourfriend/ProjectIsothermalExpert#12]
### **Confirm your current modpack version:**

```
0.3.5 (latest)
```
### **Are you on a server? Or in Singleplayer?:**

```
Singleplayer
```

### **Description:**

```
Both a golden shovel & sword can be progressed to diamond, whereas a golden pickaxe, axe & hoe cannot?
Not sure if intentional.
```

### **Steps to reproduce:**

```
JEI
```
### **Crash log (*if any*):**
> *Must use a code-pasting website such as Pastebin, or a Gist.*

```
N/A
```

**Comment by Kikiisyourfriend** [comment]
Yes, This is Intentional
