### ISSUE TITLE
[BUG] - CagedMobs JEI conflict

### ISSUE THREAD

**Issue by itsjusttriz** [Kikiisyourfriend/ProjectIsothermalExpert#13]
### **Confirm your current modpack version:**

```
0.3.5 (latest)
```
### **Are you on a server? Or in Singleplayer?:**

```
Singleplayer
```

### **Description:**

```
Caged Cat gives string, but egg is not craftable. Maybe hide it from JEI?
```

### **Steps to reproduce:**

```
N/A
```
### **Crash log (*if any*):**
> *Must use a code-pasting website such as Pastebin, or a Gist.*

```
N/A
```

**Comment by Kikiisyourfriend** [comment]
Not going to bother hiding most things from JEI. If it can't craft and is not a road block I won't deal with it.
