### ISSUE TITLE
[SUGGESTION] - Automatable tools

### ISSUE THREAD

**Issue by itsjusttriz** [Kikiisyourfriend/ProjectIsothermalExpert#14]
### **Confirm your current modpack version:**

```
0.3.5 (latest)
```
### **Are you on a server? Or in Singleplayer?:**

```
Singleplayer
```

### **Description:**

```
You told me to remind you about the (dirty tool + waterbucket) recipe for tool automation
```

### **Steps to reproduce:**

```
N/A
```
### **Crash log (*if any*):**
> *Must use a code-pasting website such as Pastebin, or a Gist.*

```
N/A
```

**Comment by Kikiisyourfriend** [comment]
Thank you.
