### ISSUE TITLE
[BUG] - Flux Networks Recipe

### ISSUE THREAD

**Issue by itsjusttriz** [Kikiisyourfriend/ProjectIsothermalExpert#16]
### **Confirm your current modpack version:**

```
0.4.0 (latest)
```
### **Are you on a server? Or in Singleplayer?:**

```
Singleplayer
```

### **Description:**

```
Flux Networks default recipe needs disabling.
```
![image](https://i.gyazo.com/95e6a489cf5a57f6c05f1a6f1d44fe5b.png)

### **Steps to reproduce:**

```
N/A
```
### **Crash log (*if any*):**
> *Must use a code-pasting website such as Pastebin, or a Gist.*

```
N/A
```

**Comment by Kikiisyourfriend** [comment]
It doesn't actually. Some psychopath might still like making it that way.
