### ISSUE TITLE
[BUG] - Some Seeds don't have Botany Pots uses

### ISSUE THREAD

**Issue by darkequine** [Kikiisyourfriend/ProjectIsothermalExpert#19]
### **Confirm your current modpack version:**

```
0.5.2 (latest)
```
### **Are you on a server? Or in Singleplayer?:**

```
Singleplayer
```

### **Description:**

```
Marble, Limestone, Apatite, Basalt seeds all have recipes, but JEI doesn't show a botany pots use like all the others do.
```

### **Steps to reproduce:**

```
None. Recipe issue.
```
### **Crash log (*if any*):**
> *Must use a code-pasting website such as Pastebin, or a Gist.*

```
None.
```

**Comment by itsjusttriz** [comment]
Tested in latest 0.5.2 and can confirm, there is no growth mechanic available for them in gameplay or in JEI.

**_Notes for Kiki_**
  
| Seed | CraftTweaker | KubeJS |
| --- | --- | --- |
| Marble | `<item:mysticalagriculture:marble_seeds>` | `'mysticalagriculture:marble_seeds'`|
| Limestone | `<item:mysticalagriculture:limestone_seeds>` | `'mysticalagriculture:limestone_seeds'` |
| Apatite | `<item:mysticalagriculture:apatite_seeds>` | `'mysticalagriculture:apatite_seeds'` |
| Basalt | `<item:mysticalagriculture:basalt_seeds>` | `'mysticalagriculture:basalt_seeds'` |

**Comment by Kikiisyourfriend** [comment]
Fixed for next update! Thank you!
