### ISSUE TITLE
GeneticsAPI startup error

### ISSUE THREAD

**Issue by itsjusttriz** [Kikiisyourfriend/ProjectIsothermalExpert#2]
Got this error on pack launch.
[image](https://gyazo.com/61c67acab8c78f53f0297b4fdbb034ff)

**Comment by itsjusttriz** [comment]
Apparently this was only a 1 time error? Still would be neat to have it not happen for new players

**Comment by Kikiisyourfriend** [comment]
Will look further into this.

**Comment by itsjusttriz** [comment]
Un-reproducable.
