### ISSUE TITLE
[Suggestion] - Add toast control mod to pack

### ISSUE THREAD

**Issue by udooles** [Kikiisyourfriend/ProjectIsothermalExpert#20]
### **Confirm your current modpack version:**
,,,
0.5.1.1
,,,
### **Are you on a server? Or in Singleplayer?:**
,,,
Singleplayer
,,,
### **Description:**
,,,
Suggestion to add a toast control mod to the pack as it's a bit of time before you harvest your first tree and the early toast messages are both annoying and overlap the GUI screen.
,,,
### **Steps to reproduce:**
,,,
Start a new game and get toast messages
,,,
### **Crash log (*if any*):**
> *Must use a code-pasting website such as Pastebin, or a Gist.*
N/A

**Comment by itsjusttriz** [comment]
There isnt a need to add an extra mod just for select peoples viewing preference. Might i suggest installing the mod on your client. It *is* a clientside mod and therefore will not interact poorly with any servers you may be playing on?

**Comment by Kikiisyourfriend** [comment]
100% this will get added in the next update.
I find it annoying as well.
