### ISSUE TITLE
[Suggestion] - Add better description how to get first water. 

### ISSUE THREAD

**Issue by udooles** [Kikiisyourfriend/ProjectIsothermalExpert#21]
### **Confirm your current modpack version:**
...
0.5.1.1
...
### **Are you on a server? Or in Singleplayer?:**
...
Singleplayer
...

### **Description:**

```
Suggestion to add better lead to "The Shrinking" page of the quest to describe how to make water.  It's a bit confusing how to get water without digging though the quest book the first time.  Consider either a check mark informational quest on the Scavange quest page or creating dependances on some of the early quests to connect the pages.
```

### **Steps to reproduce:**

```
Start a new game and follow quest book.
```
### **Crash log (*if any*):**
> *Must use a code-pasting website such as Pastebin, or a Gist.*

```
HERE
```

**Comment by itsjusttriz** [comment]
There already is a dependency. The Trigger for unlocking 'The Shrinking' chapter, is Dirty planks, found on the 'Scavange' chapter.

Also, the Shrinking page is found under the `Chapter One` category. Put 2&2 together.

Water Bloche quest has a description containing the how-to, to get the 1st water source.

This semi-issue has been brought up a couple times, with various other intents in mind. e.g. Crafting table etc.
Kiki has already refused to change the layout. Therefore I'll be discontinuing this Suggestion report. Kiki will most likely review this later on anyways, and if he feels the need, he will reinstate it.

**Comment by Kikiisyourfriend** [comment]
Triz is correct. Chapter One means that's you're first step after Scavenge.
