### ISSUE TITLE
[BUG] - Scavange quest line is misspelled 

### ISSUE THREAD

**Issue by udooles** [Kikiisyourfriend/ProjectIsothermalExpert#22]
### **Confirm your current modpack version:**

```
0.5.2 (latest)
```
### **Are you on a server? Or in Singleplayer?:**

```
Singleplayer
```

### **Description:**

```
The quest line Scavange seems to be misspelled and should be Scavenge unless it's meant to that way.
```

### **Steps to reproduce:**

```
Open quest book.
```
### **Crash log (*if any*):**
> *Must use a code-pasting website such as Pastebin, or a Gist.*

```
HERE
```

**Comment by itsjusttriz** [comment]
Kiki isnt the best with spelling, and majority of us are used to it :P Im sure he'll fix it when he can, but it wont be at the top of the list as it is not urgent to the mechanics of the pack.

**Comment by Kikiisyourfriend** [comment]
Dang it!

**Comment by Kikiisyourfriend** [comment]
I also misspelled it in some of the JEI info! F
