### ISSUE TITLE
[BUG] - piglin brute dna seem's like normal piglin

### ISSUE THREAD

**Issue by Jimwts** [Kikiisyourfriend/ProjectIsothermalExpert#23]
### **Confirm your current modpack version:**

```
0.5.2 (latest)
```
### **Are you on a server? Or in Singleplayer?:**

```
Singleplayer
```

### **Description:**

```
When i succeed to spawn a piglin brute, the dna i have is a normal piglin
```

### **Steps to reproduce:**

```
Hit a piglin brute with a dna 
```
### **Crash log (*if any*):**
> *Must use a code-pasting website such as Pastebin, or a Gist.*

```
Not a crash
```

**Comment by darkequine** [comment]
Interesting. The piglin brute worked just fine for me.

**Comment by itsjusttriz** [comment]
I have tested this on latest 0.5.2 and it works fine for me.
![image](https://i.gyazo.com/1310ee22e7e50bb55c03e313576f06f3.png)

**Comment by Kikiisyourfriend** [comment]
Only thing I can think of is you might have thought you made the Brute but just made the normal Piglin?
It works just fine.
