### ISSUE TITLE
[BUG] - Wither Bee Spawn Egg doesn't have a recipe

### ISSUE THREAD

**Issue by darkequine** [Kikiisyourfriend/ProjectIsothermalExpert#24]
### **Confirm your current modpack version:**

```
0.5.2 (latest)
```
### **Are you on a server? Or in Singleplayer?:**

```
Singleplayer
```

### **Description:**
See title.
```
HERE
```

### **Steps to reproduce:**

```
N/A
```
### **Crash log (*if any*):**
> *Must use a code-pasting website such as Pastebin, or a Gist.*

```
N/A
```

**Comment by Kikiisyourfriend** [comment]
Thank you!
