### ISSUE TITLE
[BUG] - Quest for Coal Seed still exists

### ISSUE THREAD

**Issue by darkequine** [Kikiisyourfriend/ProjectIsothermalExpert#25]
### **Confirm your current modpack version:**

```
0.5.3 (latest)
```
### **Are you on a server? Or in Singleplayer?:**

```
Singleplayer
```

### **Description:**

```
Changelog says Coal Seeds were removed, but the quest for them still exists.
```

### **Steps to reproduce:**

```
N/A
```
### **Crash log (*if any*):**
> *Must use a code-pasting website such as Pastebin, or a Gist.*

```
N/A
```

**Comment by itsjusttriz** [comment]
These will be removed for the next update
