### ISSUE TITLE
[BUG] - Limestone Seeds Exist, No way to get limestone

### ISSUE THREAD

**Issue by darkequine** [Kikiisyourfriend/ProjectIsothermalExpert#26]
### **Confirm your current modpack version:**

```
0.5.3 (latest)
```
### **Are you on a server? Or in Singleplayer?:**

```
Singleplayer
```

### **Description:**

```
You need limestone to make limestone seeds, but the only way to get limestone (that I can see) is limestone essence. No other way to make the seeds or get limestone.
```

### **Steps to reproduce:**

```
N/A
```
### **Crash log (*if any*):**
> *Must use a code-pasting website such as Pastebin, or a Gist.*

```
N/A
```

**Comment by itsjusttriz** [comment]
Kiki will test this in a bit, and may create a new method

**Comment by Kikiisyourfriend** [comment]
Thank you. Applied to next update!
