### ISSUE TITLE
[BUG] - Ink sacs unobtainable?

### ISSUE THREAD

**Issue by darkequine** [Kikiisyourfriend/ProjectIsothermalExpert#27]
### **Confirm your current modpack version:**

```
0.5.3 (latest)
```
### **Are you on a server? Or in Singleplayer?:**

```
Singleplayer
```

### **Description:**

```
Hate to post so many of these in one day, lol

Don't see a way to get ink sacs. Passive mobs don't spawn, so I can't get a DNA sample. Spawn egg doesn't have a recipe. I'm trying to fish for them, but unsure if that is part of the loot table. Otherwise, no other way to make Squid Seeds.
```

### **Steps to reproduce:**

```
N/A
```
### **Crash log (*if any*):**
> *Must use a code-pasting website such as Pastebin, or a Gist.*

```
N/A
```

**Comment by itsjusttriz** [comment]
Squid essence would be made from the Squid Egg for use in the Mobcages. If there isnt a Squid Egg Recipe, kiki will add one for next update

**Comment by darkequine** [comment]
Same thing for Guardians (for prismarine essence) and Rabbits.

**Comment by Kikiisyourfriend** [comment]
Done and ready for next update. Thank you, @darkequine and don't be sorry at all. All these reports make the pack better. Appreciate your contribution.
