### ISSUE TITLE
[BUG] - Early Game Recipe loop

### ISSUE THREAD

**Issue by itsjusttriz** [Kikiisyourfriend/ProjectIsothermalExpert#28]
### **Confirm your current modpack version:**

```
0.5.3 (latest)
```
### **Are you on a server? Or in Singleplayer?:**

```
Singleplayer
```

### **Description:**

```
https://gyazo.com/cf9f7594dbe9359583df2c94db03a77a
Make Pistons require #forge:stone again
```

### **Steps to reproduce:**

```
HERE
```
### **Crash log (*if any*):**
> *Must use a code-pasting website such as Pastebin, or a Gist.*

```
HERE
```

**Comment by Kikiisyourfriend** [comment]
Thank you.
