### ISSUE TITLE
[BUG] - *Luminous crafting table*

### ISSUE THREAD

**Issue by Jimwts** [Kikiisyourfriend/ProjectIsothermalExpert#29]
### **Confirm your current modpack version:**

```
0.5.5

```
### **Are you on a server? Or in Singleplayer?:**

```
Singleplayer

```

### **Description:**

```
Can't craft the luminous table 
![image](https://user-images.githubusercontent.com/104171724/164913481-0bc79cdf-cf4d-4d0c-a12f-73a4a9040ded.png)
What I miss ? ^^
```

### **Steps to reproduce:**

```
HERE
```
### **Crash log (*if any*):**
> *Must use a code-pasting website such as Pastebin, or a Gist.*

```
HERE
```

**Comment by itsjusttriz** [comment]
Ive poked Kiki about this. He'll reply when he can. Also Embedding images doesnt work from inside the \`\`\`, just a note 😄

**Comment by Jimwts** [comment]
Ha.. Sorry, I'm not a confirmed user of github 😅

**Comment by Kikiisyourfriend** [comment]
@Jimwts did you convert the crystal to armara?

**Comment by Jimwts** [comment]
Well, it seems that i am an idiot. 😂😂

It works fine with the conversion.

Sorry!

**Comment by Kikiisyourfriend** [comment]
It's all good! Also I meant Aevitas LOL. but GG on getting it to work!

**Comment by itsjusttriz** [comment]
Issue has been resolved 👍🏼
