### ISSUE TITLE
the charcoal is impossible to get 

### ISSUE THREAD

**Issue by ExtraCrafter** [Kikiisyourfriend/ProjectIsothermalExpert#30]
i start playing the modpack today i really love it is really well made beside that i found a bug i read the tooltip many time too get charcoal too make sure i did not mis read it is sneak right click with a stone axe on stripped spruce log so i did that but i did not get any charcoal i made more stone axe lets say 5 mins later still nothing i do everything right what the quest tell me and the tooltip i dont really know too do now then other go too creative mode too get the charcoal

**Comment by Kikiisyourfriend** [comment]
Thank you, but it's 100% not bugged. I literally just got two right now from it with one Stone Axe

**Comment by darkequine** [comment]
I believe the drop chance is pretty low. Took me a while to get my first piece as well during my playthrough. Just keep trying, you'll get one.
