### ISSUE TITLE
[BUG?] - Phantom Spawn Egg

### ISSUE THREAD

**Issue by darkequine** [Kikiisyourfriend/ProjectIsothermalExpert#31]
### **Confirm your current modpack version:**

```
0.6.0 (latest)
```
### **Are you on a server? Or in Singleplayer?:**

```
Singleplayer
```

### **Description:**

```
Can someone verify that the phantom egg is craftable? I cannot seem to get it to craft and am unsure if I'm just being a derp. I've double and triple checked the recipe. Placed and replaced all the blocks.

I have crafted other eggs just fine, but reset the field projectors just in case.
```

### **Steps to reproduce:**

```
N/A
```
### **Crash log (*if any*):**
> *Must use a code-pasting website such as Pastebin, or a Gist.*

```
N/A
```

**Comment by Kikiisyourfriend** [comment]
It does craft but Compact Crafting is a bit finicky when it comes to orientation.
Try building it looking north south east or west.
Not much I can do about this.

**Comment by darkequine** [comment]
That was it! Thank you!
