### ISSUE TITLE
[BUG] - Can't craft wooden pressure plates

### ISSUE THREAD

**Issue by DoubleDimensional** [Kikiisyourfriend/ProjectIsothermalExpert#33]
### **Confirm your current modpack version:**

```
0.6.2 (latest)
```
### **Are you on a server? Or in Singleplayer?:**

```
Singleplayer
```

### **Description:**

```
The recipe for a stick seems to be shapeless, so trying to craft a wooden pressure plate results in a stick instead.
```

### **Steps to reproduce:**

```
Place two wooden planks side-by-side in any crafting table.
```
### **Crash log (*if any*):**
> *Must use a code-pasting website such as Pastebin, or a Gist.*

```
No crash, just minor inconvenience.
```

**Comment by Kikiisyourfriend** [comment]
Thank you! This will be corrected in the next update.
