### ISSUE TITLE
[Info] - *Armara Crystal*

### ISSUE THREAD

**Issue by Jimwts** [Kikiisyourfriend/ProjectIsothermalExpert#34]
### **Confirm your current modpack version:**

```
0.6.2 (latest)
```
### **Are you on a server? Or in Singleplayer?:**

```
Singleplayer
```

### **Description:**
```
I can't find how to complete the quest " armara crystal" in astral's quests. Can you explain to me? (no recipe, no indication on the quest) 

Thx for your beautiful work! 
```

### **Steps to reproduce:**

```
HERE
```
### **Crash log (*if any*):**
> *Must use a code-pasting website such as Pastebin, or a Gist.*

```
HERE
```

**Comment by Kikiisyourfriend** [comment]
You need to know how to use Astral. If you don't I suggest looking at YouTube videos on how it works and how to Attune Rocks or Yourself. Yes you can attune yourself to a constellation and some can be OP AF. The way I have it set in the quest book is as easy to figure out if you have experience with the mod.
