### ISSUE TITLE
[SUGGESTION] - Hoe mechanics

### ISSUE THREAD

**Issue by itsjusttriz** [Kikiisyourfriend/ProjectIsothermalExpert#35]
### **Confirm your current modpack version:**
> We ask for this incase this suggestion has already been implemented in a newer version.

```
N/A
```
### **What is this suggestion focused on?:**

```
Custom Mechanics
```

### **Description:**

```
Been watching DanRobzProbz playthrough on YT. Noticed when he used the wooden hoe on farmland,
it didnt drain the durability of the hoe. Maybe correct this?
```

**Comment by Kikiisyourfriend** [comment]
The wooden hoe is not game breaking at all. This can stay this way forever and ever and ever.
