### ISSUE TITLE
[BUG] - *Clay Essence Recipe does not work in 2 by 2 grid*

### ISSUE THREAD

**Issue by THEBLACKYOSHI11** [Kikiisyourfriend/ProjectIsothermalExpert#36]
### **Are you on a server? Or in Singleplayer?:**
Singleplayer

### **Description:**

```
Clay does not create in your 2x2 grid in your inventory using earth and water essence. 
```

### **Steps to reproduce:**

```
Just try to craft in your inventory. Does work in a 3x3 grid. 
```
### **Crash log (*if any*):**
> *Must use a code-pasting website such as Pastebin, or a Gist.*

```
HERE
```

**Comment by itsjusttriz** [comment]
I feel like you may be doing something wrong as I've had this work for me countless times?

**Comment by Kikiisyourfriend** [comment]
No, @itsjusttriz they are correct lol. It 100% does not work in a 2x2 grid. I can fix this but it's very minor so don't expect it too soon, @THEBLACKYOSHI11 Thank you for bringing this up.

**Comment by itsjusttriz** [comment]
ah well then im pretty sure it was only a recent bug then as ive crafted clay from essence multiple times when i played the pack

**Comment by Kikiisyourfriend** [comment]
Turns out that is a default Mystical Agriculture recipe so that will be left alone. Thank you for bringing this to my attention tho! Happy Testing!
