### ISSUE TITLE
[BUG] - auto crafting refined of a stick

### ISSUE THREAD

**Issue by Jimwts** [Kikiisyourfriend/ProjectIsothermalExpert#38]
### **Confirm your current modpack version:**

```
0.6.2 (latest)
```
### **Are you on a server? Or in Singleplayer?:**

```
Singleplayer
```

### **Description:**

```
When i try to add the stick's recipe on refined netherrite crafter, i couldn't click on start button (greyed out). I have few crash, and i think it's when my refined system try to auto craft a stick for another recipe (like a sword for example). 
I don't know how to show you what's happening, and my game crash on loading now 😭😭
```

### **Steps to reproduce:**

```
Pattern with a stick in a netherrite crafter. 
```
### **Crash log (*if any*):**
> *Must use a code-pasting website such as Pastebin, or a Gist.*

```
HERE
```

**Comment by Kikiisyourfriend** [comment]
This was fixed in version 0.6.3 I recommend updating to the most recent update, or better yet, wait until after tonight because I will be putting out a new update for version 0.6.5
