### ISSUE TITLE
[BUG] - *TITLE_HERE*

### ISSUE THREAD

**Issue by Jimwts** [Kikiisyourfriend/ProjectIsothermalExpert#39]
### **Confirm your current modpack version:**

```
0.6.5
```
### **Are you on a server? Or in Singleplayer?:**

```
Singleplayer
```

### **Description:**

```
Crash when i launc my world
```

### **Steps to reproduce:**

```
HERE
```
### **Crash log (*if any*):**
> *Must use a code-pasting website such as Pastebin, or a Gist.*

```
https://pastebin.com/kMqyyEJZ
```

**Comment by Kikiisyourfriend** [comment]
Unfortunately this is causing issues with anyone who has a Refined Storage Pattern for Minecraft Stick when I had to make the recipe conflict change from version 0.6.2. Might I suggest downgrading to that version, removing the Stick pattern all together and then updating again. (Idk why I didn't think of this when I was crashing LOL)

**Comment by Jimwts** [comment]
Do the downgrading, remove the pattern, update again, encode a pattern for the stick, crash again with the same error.
I think it's when the system auto craft for a craft card (i have an exporter for diamond sword with a craft card for add a diamond sword in an item user).

Don't worry, i just craft myself my stick, but i prefer to explain the bug for other user 😊

**Comment by Kikiisyourfriend** [comment]
@Jimwts You might have to make a new recipe again for the pickaxe and possibly for all items that used stick. @itsjusttriz did warn me that this might happen but I didn't think it would. Try that and if it works Triz can call me a dumb dumb.

**Comment by itsjusttriz** [comment]
*prepares the MEGA "dumb dumb"*
