### ISSUE TITLE
Cant craft iron nuggets for water

### ISSUE THREAD

**Issue by Ethan-Dankiw** [Kikiisyourfriend/ProjectIsothermalExpert#4]
water -> bucket -> iron nuggets -> stone pickaxe on andesite -> wooden pickaxe + stone -> dirty pickaxe in water -> water

Version 0.3.0

**Comment by itsjusttriz** [comment]
Thankyou for reporting this issue. This will be investigated as soon as possible.

**Comment by itsjusttriz** [comment]
Ah yea i see the issue now. The water bucket quest currently gives the water to be able to transform the dirty pickaxe to a wooden_pickaxe for the above crafting path. This isnt achieveable without iron, which is the purpose of the water bucket quest. It's a un-achieveable loop. @Kikiisyourfriend

**Comment by Kikiisyourfriend** [comment]
This issue has a temporary fix. Will look into a cool craft later on tonight on stream.

https://www.curseforge.com/minecraft/modpacks/project-isothermal-expert/files/3752399

**Comment by Kikiisyourfriend** [comment]
This issue is now fixed! Thank you for your contribution!
