### ISSUE TITLE
cant install

### ISSUE THREAD

**Issue by zacharypsp** [Kikiisyourfriend/ProjectIsothermalExpert#40]
### **Confirm your current modpack version:**

```
1.0.1(latest) i have tried others 
```
### **Are you on a server? Or in Singleplayer?:**

```
Singleplayer
```

### **Description:**

```
i cant install it on curseforge launcher i have not tried other launchers
if i download the zip and try to import i get curse.radium.installmanagement.installtaskfailedexception
and if i try to download it in the launcher i get object reference not set to an instance of an object
```

### **Steps to reproduce:**

```
try to install
```
### **Crash log (*if any*):**
> *Must use a code-pasting website such as Pastebin, or a Gist.*

```
HERE
```

**Comment by darkequine** [comment]
Curseforge has been having server issues yesterday/today. I do not believe that this is a pack problem, more of a Curseforge problem. Try it again in a few hours is my suggestion.

**Comment by Kikiisyourfriend** [comment]
This is 100% not a pack problem or else I would have been swarmed with reports. @zacharypsp This does seem like a curse issue of some kind since curseforge was having issues earlier for a couple of days now.
