### ISSUE TITLE
Mob Cage Environment not being recognized

### ISSUE THREAD

**Issue by Joe106** [Kikiisyourfriend/ProjectIsothermalExpert#42]
### **Confirm your current modpack version:**

```
1.0.2 (latest)
```
### **Are you on a server? Or in Singleplayer?:**

```
Singleplayer
```

### **Description:**

```
I am trying to get Dye Essence, and when I try to right click on the Hopping Mob Cage with a Zombie Villager DNA Sample,
it says that I still need to setup the environment.  However, I have placed Diamond Ore underneath the Hopping Mob
Cage, so I am not sure what it is wanting me to do.
```

### **Steps to reproduce:**

```
The exact steps I did were, 1) Placing down the Diamond Ore, 2) Placing the Hopping Mob Cage on top of said Diamond Ore,
then 3) Right clicking with a DNA Sampler filled with Zombie Villager DNA.  After this, it gives the message, "You need
to set up an Environment first."
```
### **Crash log (*if any*):**
> *Must use a code-pasting website such as Pastebin, or a Gist.*

```
No Crash Log.
```

**Comment by Joe106** [comment]
Sorry about this, I just found out that I was still on version 0.6.3.  Curseforge is being weird since I assumed it would ask me to update it.  Please disregard this question for now.

**Comment by itsjusttriz** [comment]
@Joe106 regardless of what version you're on. The diamond ore goes inside the cage, not under it.

**Comment by Joe106** [comment]
Thank you for the comment.  I have never used the Mob Cage mod, and it seemed like I had to put the block underneath the Mob Cage rather than inside it by how it was explained on the Curseforge page for the mod.

**Comment by itsjusttriz** [comment]
@Joe106 No problem! I have copied the mods wiki to the wiki tab above ^ Ive just re-read it and it seems to make sense immediately :) Hope it helps.
