### ISSUE TITLE
[BUG] - Recipes using Spent Nuclear Waste not working

### ISSUE THREAD

**Issue by gaminggirl** [Kikiisyourfriend/ProjectIsothermalExpert#45]
### **Confirm your current modpack version:**

```
1.0.8
```
### **Are you on a server? Or in Singleplayer?:**

```
Singleplayer
```

### **Description:**

```
When trying to make Polonium Pellets from Spent Nuclear Waste the spent Nuclear Wate is stuck in the Gas Tube and can't get into the Antiprotonic Nucleosynthesizer or into a Chemical Tank. Same thing happens if I try to make Nuclear Waste in the Chemical Infuser to. 
```

### **Steps to reproduce:**

```
Get Spent Nuclear Wast into a tube or waste barrel, then pipe it to a Antiprotonic Nucleosynthesizer or a Chemical Infuser or a Chemical Tank. Waste stays in the pipe and machine stays empty. 
```
### **Crash log (*if any*):**
> *Must use a code-pasting website such as Pastebin, or a Gist.*

```
No crash.
```

**Comment by Kikiisyourfriend** [comment]
We are aware of this. After making this recipe we found out that the Mekanism devs do not let Nuclear Waste be recycled.
I couldn't be bothered to remove the recipes.
