### ISSUE TITLE
[BUG] - *"No valid items" for xnet:connectors*

### ISSUE THREAD

**Issue by CarlSmotricz** [Kikiisyourfriend/ProjectIsothermalExpert#48]
### **Confirm your current modpack version:**

```
1.0.8 (latest)
```
### **Are you on a server? Or in Singleplayer?:**

```
Online Multiplayer Server
```

### **Description:**

```
On the "EVERYTHING" quest page, for XNet connectors, clicking on the "view recipe" link
for the "connector" quest yield "no valid items".
Ditto for `xnet:cables` .
```

### **Steps to reproduce:**

```
Click on the XNet connector quest, then the "view recipe" link for that quest.
```
### **Crash log (*if any*):**
> *Must use a code-pasting website such as Pastebin, or a Gist.*

```
N/A
```

**Comment by itsjusttriz** [comment]
@CarlSmotricz This is already known. Its out of our control.
