### ISSUE TITLE
Few Bugs

### ISSUE THREAD

**Issue by Ethan-Dankiw** [Kikiisyourfriend/ProjectIsothermalExpert#5]
### **Confirm your current modpack version:**
0.3.3 - *latest*

### **Are you on a server? Or in Singleplayer?:**
Singleplayer

### **Description:**
1. 'Sanguine Scientiem' missing for altar layout (edit: thermalpedia as well)
2. Demonite quest requires a Redstone furnace as a prerequisite despite smelting in a regular furnace
3. Dagger of Sacrifice doesn't work on Dungeon Metal Block to get demonic will
4. Enderman spawn egg quest missing regular egg prerequisite. 
5. Stoneling DNA won't go in a mob cage (error: 'The environment inside the cage is not suitable for this entity')

**Comment by itsjusttriz** [comment]
Referencing No.5, There's a typo in the `kubejs/data/quark/recipes/mobs/stoneling.json` thats faulting the entry data. We will have this fixed for next update.

Regarding the others, we'll wait for a response from Kiki.

**Comment by Kikiisyourfriend** [comment]
1. Documentation for Blood Magic and Thermal do not exist at least not that I can see. I don't have anything disabled for that. Added Image for Tier 5 Blood Altar instead.
2. Demonite quest now fixed.
3. Dagger of Sacrifice has always worked. It's just a 1% change for them. It's now documented in the Quest Book.
4. Endermand Spawn Egg now has Dependency.
5. Stoneling Fixed.

**Comment by itsjusttriz** [comment]
@PxlRift Correction, the books **did** exist. He was just shown that he had previously hidden them from jei. This is corrected for the next update.
