### ISSUE TITLE
[BUG] - *Rock crystal ore description mistake*

### ISSUE THREAD

**Issue by Infinituum17** [Kikiisyourfriend/ProjectIsothermalExpert#58]
### **Confirm your current modpack version:**

```
1.0.8 (latest)
```
### **Are you on a server? Or in Singleplayer?:**

```
Singleplayer
```

### **Description:**

```
While searching for a way to obtain Rock Crystal Ore I noticed a mistake in the description: you are meant to use the Fluxbore on a Emerald Ore block (as it is said in other ores that you can obtain) but the description in JEI tells you to use it on an Emerald Block
```

### **Steps to reproduce:**

```
Click on Rock Crystal Ore in JEI
```
### Rock Crystal Ore
![image](https://user-images.githubusercontent.com/40234342/197201333-5506fb48-2922-4c86-a479-02520044b546.png)
### Prosperity Ore
![image](https://user-images.githubusercontent.com/40234342/197201424-1b74d91d-ac32-413a-a907-1f846fdb6415.png)

**Comment by Kikiisyourfriend** [comment]
Oh piss! Thank you for finding this mistake.
