### ISSUE TITLE
[BUG] - *Can't craft tunnels from Compact Machines' mod*

### ISSUE THREAD

**Issue by Infinituum17** [Kikiisyourfriend/ProjectIsothermalExpert#60]
### **Confirm your current modpack version:**

```
1.0.8 (latest)
```
### **Are you on a server? Or in Singleplayer?:**

```
Singleplayer
```

### **Description:**

```
Tunnels from Compact Machines 4 are uncraftable
```

**Comment by Kikiisyourfriend** [comment]
This, unfortunately, is not a modpack issue but rather a mod issue because they are in JEI but the mod creator never implemented them. I even wanted a recipe using these but it was not possible.
Will check eventually if there was a mode update that fixes this.
