### ISSUE TITLE
[BUG] - *pack not launching correctly*

### ISSUE THREAD

**Issue by filloba** [Kikiisyourfriend/ProjectIsothermalExpert#62]
### **Project Isothermal Expert-1.0.8.zip:**

```
1.0.2 (latest)
1.0.8
```
### **Are you on a server? Or in Singleplayer?:**

```
Singleplayer
```

### **Description:**

```
after launch the pack simply close during the loading
```

### **Steps to reproduce:**

```
launch from minecraft launcher
```
### **Crash log (*if any*):**
> *Must use a code-pasting website such as Pastebin, or a Gist.*

```
The game crashed whilst rendering overlay
Error: net.minecraftforge.fml.config.ConfigFileTypeHandler$ConfigLoadingException: Failed loading config file pipez-client.toml of type CLIENT for modid pipez
```

**Comment by filloba** [comment]
simply save your world and reinstall the pack

**Comment by itsjusttriz** [comment]
@filloba You could've also just deleted the config for Pipez mod and relaunched the modpack. It wouldve re-installed the config, fresh.

**Comment by filloba** [comment]
Thank you so much! Next time i will do this. Never happened before so i was a little bit worried

**Comment by itsjusttriz** [comment]
All good :) But for future reference. Always check that a mod's config hasnt been specifically configured for certain modpacks before deleting. As deleting, will reset the config from before the pack dev had configured it, leaving your instance different to the rest.
