### ISSUE TITLE
[BUG] - Spent Nuclear Waste doesnt go anywhere

### ISSUE THREAD

**Issue by paninucuspechi** [Kikiisyourfriend/ProjectIsothermalExpert#64]
### **Confirm your current modpack version:**
1.0.8 (latest)
```
### **Are you on a server? Or in Singleplayer?:**
<!-- Erase the options that do not match your issue, below -->
```
Singleplayer
```

### **Description:**
<!-- Answer inside the backticks -->
```
It's not possible to put Spent Nuclear Waste into Antiprotonic Nucleosynthesizer, tried all the cable existing in the pack
```

### **Steps to reproduce:**
<!-- Answer inside the backticks -->
```
Simply try to put Spent Nuclear Waste into the machine, even in creative mode, it doesn't work, the Spent Nuclear Waste is stuck into the cable
```
### **Crash log (*if any*):**
> *Must use a code-pasting website such as Pastebin, or a Gist.*
<!-- Answer inside the backticks -->
```
HERE
```

**Comment by itsjusttriz** [comment]
This issue has already been posted by another. See Issue #45.
