### ISSUE TITLE
[BUG] - Crafting item

### ISSUE THREAD

**Issue by Grassway** [Kikiisyourfriend/ProjectIsothermalExpert#66]
### **Confirm your current modpack version:**

```


1.0.8 (latest)
```
### **Are you on a server? Or in Singleplayer?:**

```

LAN Server

```

### **Description:**

```
I no longer have the modified item crafting, but i have the normal item crafting 
```

### **Steps to reproduce:**

```
I don't know, suddenly entering the world I found it like this
```
### **Crash log (*if any*):**
> *Must use a code-pasting website such as Pastebin, or a Gist.*

```
HERE
```

**Comment by Kikiisyourfriend** [comment]
Something must have corrupted on your end. Either during play through or when you downloaded the file.
I suggest downloading the files again from curse and manually replace the Script and KibeJS files only and load up your pack.

**Comment by itsjusttriz** [comment]
This was an issue on Curseforge's end. With certain changes that Mojang had made to their launchers, it had messed with the way curseforge handles modpack distribution. This has since been fixed.
