### ISSUE TITLE
[BUG] - crafting

### ISSUE THREAD

**Issue by ilgodz** [Kikiisyourfriend/ProjectIsothermalExpert#67]

**Comment by Kikiisyourfriend** [comment]
Something must have corrupted on your end. Either during play through or when you downloaded the file.
I suggest downloading the files again from curse and manually replace the Script and KibeJS files only and load up your pack.

**Comment by itsjusttriz** [comment]
This was an issue on Curseforge's end. With certain changes that Mojang had made to their launchers, it had messed with the way curseforge handles modpack distribution. This has since been fixed.
