### ISSUE TITLE
[all kubejs recipes don't exist] - *RECIPES*

### ISSUE THREAD

**Issue by trollface40076** [Kikiisyourfriend/ProjectIsothermalExpert#68]
### **Confirm your current modpack version:**

```
1.0
1.0.1
1.0.2 (latest)
```
### **Are you on a server? Or in Singleplayer?:**

```
Singleplayer
LAN Server
Online Multiplayer Server
```

### **Description:**

```
HERE
```

### **Steps to reproduce:**

```
HERE
```
### **Crash log (*if any*):**
> *Must use a code-pasting website such as Pastebin, or a Gist.*

```
HERE
```

**Comment by Kikiisyourfriend** [comment]
Something must have corrupted on your end. Either during play through or when you downloaded the file.
I suggest downloading the files again from curse and manually replace the Script and KibeJS files only and load up your pack.

**Comment by trollface40076** [comment]
which files?

Il giorno mar 8 nov 2022 alle 00:21 Kikiisyourfriend <
***@***.***> ha scritto:

**Comment by itsjusttriz** [comment]
This was an issue on Curseforge's end. With certain changes that Mojang had made to their launchers, it had messed with the way curseforge handles modpack distribution. This has since been fixed.
