### ISSUE TITLE
[BUG] - All ExpertMode crafting are disable and a FancyMenu mod appear

### ISSUE THREAD

**Issue by SparkleBoom** [Kikiisyourfriend/ProjectIsothermalExpert#69]
### **Confirm your current modpack version:**

```
1.0.8 (latest)
```
### **Are you on a server? Or in Singleplayer?:**

```
Singleplayer
```

### **Description:**

```
All ExpertMode crafting are disable. 
But a strange menu appear by default. It's called FancyMenu UI.
It can be toggle with CTRL+ALT+C .
Never saw it, never installed, never toggled.
Also all pattern (refined storage) with disabled recipes are corrupted or disappeared. To be more precise:
- Inside Crafter linked to Refined Controller directly, patterns with disable recipe are marke has "Invalid pattern"
- Inside Crafter linked to machinery (like thermal or mekanisk), patterns with disable recipe are totally disappeared
Last thing, pack splash screen is changed and even a backup from yesterday (pack totally working) doesn't resolve the issue
```

### **Steps to reproduce:**

```
Just open latest version from CursForge launcher
```
### **Crash log (*if any*):**
> *Must use a code-pasting website such as Pastebin, or a Gist.*

```
No crash
```

**Comment by Kikiisyourfriend** [comment]
My pack has not been updated in months. This sounds like some kind of corrupting on either your end or when you updated the launcher and Curse broke something.
Only thing I can suggest is manually downloading the pack from Curse and replace the Script and KubeJS folders and try again.

**Comment by zaronc** [comment]
Exactly the same thing here, same version 1.0.8: FancyUI menu appears on top of the screen and KubeJS recipes are gone.
Actually the Minecraft launcher ran an update when i launched the modpack... that's broke something...
However I install a clean version of the pack, created a new world but the problem still exists

**Comment by itsjusttriz** [comment]
This was an issue on Curseforge's end. With certain changes that Mojang had made to their launchers, it had messed with the way curseforge handles modpack distribution. This has since been fixed.
