### ISSUE TITLE
[BUG] - Quark Backpack inaccessible

### ISSUE THREAD

**Issue by itsjusttriz** [Kikiisyourfriend/ProjectIsothermalExpert#7]
### **Confirm your current modpack version:**
> *Erase the options that do not match your issue, below*
```
0.3.3 (latest)
```
### **Are you on a server? Or in Singleplayer?:**
> *Erase the options that do not match your issue, below*
```
Singleplayer
```

### **Description:**
> *Answer inside the backticks*
```
The Quark backpack requires another mod to be craftable.
https://gyazo.com/1e0c5f99908bac51edf64d61a785259f

Either hide the backpack from JEI or add the extra mod?
```

### **Steps to reproduce:**
> *Answer inside the backticks*
```
search `@quark backpack` in JEI
```
### **Crash log (*if any*):**
> *Paste URL inside the `()`. Must use a code-pasting website such as Pastebin, or a Gist.*
```
N/A
```

**Comment by Kikiisyourfriend** [comment]
Good find but it will remain disabled.
