### ISSUE TITLE
[BUG] - all hard recipes are no longer present

### ISSUE THREAD

**Issue by gaeconci** [Kikiisyourfriend/ProjectIsothermalExpert#70]
### **Confirm your current modpack version:**

```
1.0.8
```
### **Are you on a server? Or in Singleplayer?:**

```
Singleplayer

```

### **Description:**

```
all hard recipes are no longer present and I don't know how to solve
```

### **Steps to reproduce:**

```
HERE
```
### **Crash log (*if any*):**
> *Must use a code-pasting website such as Pastebin, or a Gist.*

```
HERE
```

**Comment by gaeconci** [comment]
I also tried uninstalling and installing the modpack but nothing cmabia, even creating a new world

**Comment by gaeconci** [comment]
maybe I found the problem, if I try to install the simple storage the hard crafting is lost 

edit. I have tried removing the mod, deleting curseforge and reinstalling it but the problem remains

**Comment by itsjusttriz** [comment]
This was an issue on Curseforge's end. With certain changes that Mojang had made to their launchers, it had messed with the way curseforge handles modpack distribution. This has since been fixed.
