### ISSUE TITLE
Server Create

### ISSUE THREAD

**Issue by AndyCare04** [Kikiisyourfriend/ProjectIsothermalExpert#71]
Hi is there a method to create a server with this package?

**Comment by itsjusttriz** [comment]
Server files will be released soonTM

Theyve been on my todo list for a bit, just never got around to doing them yet.

**Comment by itsjusttriz** [comment]
@AndyCare04 Server files have been posted! \o/ They must be used with v1.0.8 of the modpack.

Get them [HERE](https://www.curseforge.com/minecraft/modpacks/project-isothermal-expert/files/4434841).
