### ISSUE TITLE
[BUG] - *TITLE_HERE*

### ISSUE THREAD

**Issue by realisaac0** [Kikiisyourfriend/ProjectIsothermalExpert#75]
### **Confirm your current modpack version:**

```
1.0.8 (latest)
```
### **Are you on a server? Or in Singleplayer?:**

```
Singleplayer

```

### **Description:**

```
autocrafting sticks with rftools autocrafter does not work
```

### **Steps to reproduce:**

```
using RFToolsUtility crafter T1, place stick recipe and crafter for automation
--> crafter will not autocraft said stick recipe
```
### **Crash log (*if any*):**
> *Must use a code-pasting website such as Pastebin, or a Gist.*

```
none
```

**Comment by itsjusttriz** [comment]
Duplicate of #53
