### ISSUE TITLE
I want to play this pack multiplayer but I can't find files for servers

### ISSUE THREAD

**Issue by himhimbb9** [Kikiisyourfriend/ProjectIsothermalExpert#76]
Will this pack support multiplayer in the later release so I can play with my friend.

**Comment by itsjusttriz** [comment]
SoonTM

**Comment by itsjusttriz** [comment]
@himhimbb9 Server files have been posted \o/ 

Get them [HERE](https://www.curseforge.com/minecraft/modpacks/project-isothermal-expert/files/4434841).
