### ISSUE TITLE
[BUG] - When place disk drive crash

### ISSUE THREAD

**Issue by ceopet08** [Kikiisyourfriend/ProjectIsothermalExpert#78]
### **Confirm your current modpack version:**

```
1.0.4
```
Singleplayer

### **Description:**

```
when i place the disk drive it crash for onknown reason for me but i think that there is something with the rs node
```

### **Steps to reproduce:**

```
place the controlloer than at the bottom place the disk drive
```
### **Crash log (*if any*):**
> *Must use a code-pasting website such as Pastebin, or a Gist.*

```
The game crashed whilst exception ticking world
Error: java.lang.ClassCastException: edivad.extrastorage.nodes.AdvancedCrafterNetworkNode cannot be cast to com.refinedmods.refinedstorage.apiimpl.network.node.diskdrive.DiskDriveNetworkNode
```
[crash-2023-05-09_22.30.27-server.txt](https://github.com/Kikiisyourfriend/ProjectIsothermalExpert/files/11436026/crash-2023-05-09_22.30.27-server.txt)

**Comment by itsjusttriz** [comment]
@ceopet08 Try updating to 1.0.8 (*latest*) of Project Isothermal, and then if the issue continues come back here.

**Comment by ceopet08** [comment]
hey it doesent work but this time i didn t even placed the drive and only 2 cables and it crash 
this is the issue:
The game crashed whilst exception ticking world
Error: java.lang.ClassCastException: com.refinedmods.refinedstorage.apiimpl.network.node.ImporterNetworkNode cannot be cast to com.refinedmods.refinedstorage.apiimpl.network.node.CableNetworkNode

**Comment by itsjusttriz** [comment]
@ceopet08 Im gonna need the full error log.

**Comment by ceopet08** [comment]
ok good how can i pass the full error to you?

**Comment by ceopet08** [comment]
ok here is the full error
[crash-2023-05-11_21.56.05-server.txt](https://github.com/Kikiisyourfriend/ProjectIsothermalExpert/files/11455913/crash-2023-05-11_21.56.05-server.txt)

**Comment by ceopet08** [comment]
how many time i have to  wait for a solution.
thanks.

**Comment by itsjusttriz** [comment]
@ceopet08 You'd get an answer quicker by posting that crash log to the Issue tracker of both, RefinedStorae & ExtraStorage mods. That's issue is caused by something internal to those 2 mods, and isnt something we can help with. Apologies.
