### ISSUE TITLE
Disk drive crash

### ISSUE THREAD

**Issue by ceopet08** [Kikiisyourfriend/ProjectIsothermalExpert#79]
### **Confirm your current modpack version:**

```
1.0.8
```
### **Are you on a server? Or in Singleplayer?:**

```
Singleplayer
```

### **Description:**

```The disk drive crash 
```

### **Steps to reproduce:**

```
HERE
```
[crash-2023-05-20_10.53.01-server.txt](https://github.com/Kikiisyourfriend/ProjectIsothermalExpert/files/11521929/crash-2023-05-20_10.53.01-server.txt)

**Comment by itsjusttriz** [comment]
[REF: #78]

Please dont create more than one "issue" for the same problem. Keep to the one we had already.

**Comment by ceopet08** [comment]
ok, but its been two weeks and i still dont know how to fix it

**Comment by itsjusttriz** [comment]
> ok, but its been two weeks and i still dont know how to fix it

I have replied in #78
