### ISSUE TITLE
[SUGGESTION] - Todo List

### ISSUE THREAD

**Issue by itsjusttriz** [Kikiisyourfriend/ProjectIsothermalExpert#8]
### `/skyblock create`
> Silverne did research and found out that in the `/config/skyblockbuilder/common-config.json5` config file, it gives an option named `createOwnTeam` which is defaulted to false, reversing this should allow non-ops to create teams.
>
>
>Having this ability will also render the need for custom chat commands useless :) Less coding hassle.

### Stoneling Caged Mobs
>There's a typo and in the `kubejs/data/quark/mobs/recipe/stoneling.json` that prevents the mob from being placed into a mobcage.
>
>Also mobs output doesnt mirror what is displayed on JEI for that mob.

**Comment by Silverne84** [comment]
Stoneling has 2 recipes, 1 in the above mentioned folder and the one created by kiki in the scripts/dna.zs. consider removing from dna.zs and editing the stoneling.json to include (chance: 1 output: essence) shorthanded for ease. Edit the output section as needed for remove unwanted items. Duplicate recipes can be seen in JEI of the mob cage page 14 and 24.

**Comment by itsjusttriz** [comment]
Bats also have no output, in the cage, it seems?

**Comment by Silverne84** [comment]
Correction to last post:
In dna.zs change:
line 29: val stoneling = entities.getEntity("quark:mobs/stoneling");
line 70: remove or comment out. I swapped it for stoneling.setTier(1); in order to mimic original design.

continue to remove typo from stoneling.json in kjs data folder.

**Comment by Kikiisyourfriend** [comment]
Config enabled!
