### ISSUE TITLE
[BUG] - Astral Quest Loop

### ISSUE THREAD

**Issue by itsjusttriz** [Kikiisyourfriend/ProjectIsothermalExpert#9]
### **Confirm your current modpack version:**
> *Erase the options that do not match your issue, below*
```
0.3.3 (latest)
```
### **Are you on a server? Or in Singleplayer?:**
> *Erase the options that do not match your issue, below*
```
Singleplayer
```

### **Description:**
> *Answer inside the backticks*
```
The `Luminous Crafting Table` quest depends on the completion of `Aevitas Celestial Collection Crystal` which is later
on down the Astral questline, and depends on... you guessed it.. The `Luminous Crafting Table` quest. Its looped and
therefore uncompletable, from my eyes.
```

### **Steps to reproduce:**
> *Answer inside the backticks*
```
Check Questbook C4
```
### **Crash log (*if any*):**
> *Paste URL inside the `()`. Must use a code-pasting website such as Pastebin, or a Gist.*
```
N/A
```

**Comment by Kikiisyourfriend** [comment]
You blind AF
